language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: nosetests --cover-branches --with-coverage --cover-erase --cover-package=practice --cover-html --cover-tests